### PR TITLE
Material UI proposal

### PR DESCRIPTION
**Pull request by DavidBachmann**
Switch out some of our `styled-jsx` and complex home made components for MaterialUI components for easier maintainability, and the ability to develop quicker.

**Includes a better date picker:**
image

**Full overview:**
image

### CODE REVIEW

**Comment by thorsteinsson** [comment]
- I'd like to remove the boxes around the file picker and radio boxes and try to keep the label style and positioning consistent.
- Why is there a line left of the cancel button?
- I'm not sure about the position of the submit buttons, I think users might click the Fab to save. Maybe make the modal on top of the Fab?

**Comment by darkowic** [comment]
I would like to recommend new material ui 1.0.0 beta but I'm not sure if all the components you use are already implemented. I use the beta material ui and its great!

**Comment by eirikurn** [comment]
I agree with @darkowic. I think it could solve some issues we ran into, eg inconsistent Labels. The Label component is simpler and more reusable in 1.0 beta.

**Comment by DavidBachmann** [comment]
@thorsteinsson I have addressed your points, see updated screenshot.

@darkowic, @eirikurn, we will definitely migrate to version 1 when it's ready.

**Comment by darkowic** [comment]
I would recommend to do it now to not duplicate the work. API in 1.0 is completely different and upgrading to 1.0 is basically rewriting all components. BTW many changes in this PR that are not related to the components :/

**Pull request closed without merging**
